Prefer the package from mkopinsky/zxcvbn-php
dhensby/silverstripe-zxcvbn pull request #1
Opened 2019-03-14 17:23 UTC by TheBnl

The original package `bjeavons/zxcvbn-php` has a difference with the original js version `dropbox/zxcvbn`. This causes checks to pass on the frond end while failing in the back end thus giving a frustrating user experience. The fork from mkopinsky fixes this issue and is more actively maintained.

2019-03-20 09:06 UTC, dhensby requested changes
I'm skeptical that this lib is any more actively maintained given that they were both last updated in 2018... but if this gives a more consistent experience with front and back-end, then ok.

2019-03-20 09:06 UTC, dhensby commented on composer.json
> +        "mkopinsky/zxcvbn-php": "*"
We can't hook onto `*` as a version constraint. `^4` would be what we want

2019-03-21 15:42 UTC, TheBnl commented
It's probably just as actively maintained as the original JS version, which has not seen any active development since 2 years 😉

But the fork does add for a more consistent experience! 
I've added the version constraint 👍

2019-03-21 17:35 UTC, dhensby approved these changes

2019-03-21 17:39 UTC, merged

2019-03-21 17:40 UTC, dhensby commented
released as 0.2.0

2019-09-26 03:45 UTC, mkopinsky commented
If the dropbox version ever picks up steam again, my PHP fork will keep up with the dropbox changes. I'm not motivated enough to fork the dropbox version so as to improve it, but I am motivated enough to keep the PHP version up to date.